# Generated by Django 4.2.3 on 2023-07-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
