# Generated by Django 4.2.3 on 2023-07-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notice',
            new_name='notices',
        ),
    ]
