# Generated by Django 4.2.3 on 2023-07-29 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0008_rename_notice_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='notice_image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
