# Generated by Django 4.2.3 on 2023-07-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0009_alter_notices_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='notice_image',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
