# Generated by Django 4.2.3 on 2023-07-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tilottama', '0004_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_by', models.CharField(default=None, max_length=50, null=True)),
                ('notice_title', models.CharField(default=None, max_length=50, null=True)),
                ('notice_description', models.TextField()),
                ('notice_image', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
