# Generated by Django 4.2.3 on 2023-07-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0006_rename_notice_notices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notices',
            new_name='Notice',
        ),
    ]
