# Generated by Django 4.2.3 on 2023-07-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0007_rename_notices_notice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Notices',
        ),
    ]
