# Generated by Django 4.2.3 on 2023-07-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0011_alter_notices_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='notice_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image'),
        ),
    ]
