# Generated by Django 4.2.4 on 2023-08-04 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0013_department_studentid_subject_student_studentsmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sutdent_age',
            new_name='student_age',
        ),
    ]
