# Generated by Django 4.2.4 on 2023-08-05 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0014_rename_sutdent_age_student_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='tilottama.student'),
        ),
    ]
