# Generated by Django 4.2.4 on 2023-08-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tilottama', '0015_alter_studentsmarks_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsmarks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mark', to='tilottama.student'),
        ),
    ]
